# Site settings
title: Paulonia Handbook
short_title: Paulonia Handbook
description: Manual para no enloquecer
baseurl: ""
handbooks_path: "paulonia_handbook"
url: "http://opendatahandbook.org" # the base hostname & protocol for your handbook site
home: "https://paulonia.dev" # the base hostname & protocol for your main company site
company_logo: paulonia.png
github_username:  PauloniaAQP
github_repo:  paulonia_handbook
contact: https://paulonia.dev/contacto


handbook_leader_name: Christofer Ch√°vez

devs:
  -
      name: Sam Smith
      github: mintcanary

contributors:
  -
      name: Rufus Pollock
      link: http://rufuspollock.org/



#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "paulonia_handbook/backend"
    values:
      layout: page
      section: Paulonia Cloud Handbook
  -
    scope:
      path: "paulonia_handbook/studios"
    values:
      layout: page
      section: Paulonia Studios Handbook
  -
    scope:
      path: "paulonia_handbook/development"
    values:
      layout: page
      section: Paulonia Development Handbook
  -
    scope:
      path: "paulonia_handbook/commercial"
    values:
      layout: page
      section: Paulonia Commercial Handbook
  -
    scope:
      path: "paulonia_handbook/paulonia"
    values:
      layout: page
      section: Paulonia Handbook
  -
    scope:
      path: "paulonia_handbook/contribute"
    values:
      layout: page
      section: Contribute
